import type { Metadata } from "next";
import "../../app/globals.css";
import MainContent from "../(admin)/admin/_components/MainContent";
import PageLoader from "../(admin)/admin/_components/PageLoader";
import { BiMenu } from "react-icons/bi";

export const metadata: Metadata = {
  title: 'CRM Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className="font-poppins overflow-x-hidden">
        <div className="w-full flex relative">
          {/** <Header /> */}
          <div className={`bg-gray-50 flex-grow max-w-[100%] duration-300 min-h-screen ml-0`}>
            <div className='w-full bg-white h-16 px-4 flex items-center drop-shadow fixed z-20'>
              <div><BiMenu size={28} /></div>
              <div className='flex-grow flex items-center justify-center font-bold'>Dev Tools</div>
            </div>
            <div className='pt-20 pb-6 px-3 2xs:px-5 z-10'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
