
export const temp_codes = [
    { "code": "{{firstname}}", "description": "User's firstname" },
    { "code": "{{lastname}}", "description": "User's lastname" },
    { "code": "{{email}}", "description": "User's primary email" },
    { "code": "{{secondary_email}}", "description": "User's secondary email" },
    { "code": "{{phone_1}}", "description": "User's primary phone number" },
    { "code": "{{phone_2}}", "description": "User's alternative phone number" },
    { "code": "{{work_phone}}", "description": "User's work phone number" },
    { "code": "{{fax}}", "description": "User's fax" },
    { "code": "{{street_address}}", "description": "User's street address" },
    { "code": "{{city}}", "description": "User's city" },
    { "code": "{{state}}", "description": "User's state" },
    { "code": "{{zip}}", "description": "User's zip code" },
    { "code": "{{country}}", "description": "User's country of origin" },
    { "code": "{{price_range}}", "description": "User's search price range" },
    { "code": "{{spouse_name}}", "description": "User's spouse name" },
    { "code": "{{birthday}}", "description": "User's birthday" },
    { "code": "{{facebook}}", "description": "User's facebook profile" },
    { "code": "{{linkedin}}", "description": "User's linkedin profile" },
    { "code": "{{x/twitter}}", "description": "User's x/twitter twitter" },
    { "code": "{{tictoc}}", "description": "User's tictoc profile" },
    { "code": "{{whatsapp}}", "description": "User's whatsapp number" },
    { "code": "{{background}}", "description": "User's background" },
    { "code": "{{broker_company_name}}", "description": "Broker's company name" },
    { "code": "{{broker_default_email}}", "description": "Broker's default email" },
    { "code": "{{broker_phone_number}}", "description": "Broker's phone number" },
    { "code": "{{broker_contact_us_email}}", "description": "Broker's contact-us email" },
    { "code": "{{broker_buying_email}}", "description": "Broker's buying request email" },
    { "code": "{{broker_selling_email}}", "description": "Broker's selling request email" },
    { "code": "{{broker_address_1}}", "description": "Broker's address 1" },
    { "code": "{{broker_address_2}}", "description": "Broker's address 2" },
    { "code": "{{broker_facebook}}", "description": "Broker's facebook page" },
    { "code": "{{broker_instagram}}", "description": "Broker's instagram page" },
    { "code": "{{broker_x/twitter}}", "description": "Broker's twitter page" },
    { "code": "{{broker_youtube}}", "description": "Broker's youtube page" },
    { "code": "{{primary_logo_link}}", "description": "Broker's primary logo link" },
    { "code": "{{secondary_logo_link}}", "description": "Broker's secondary logo link" },
]