import type { Metadata } from "next";
import "../../../globals.css";
import "../../../../CkEditor/content-styles.css";
import { Providers } from "../GlobalRedux/provider";
import PageLoader from "../_components/PageLoader";

export const metadata: Metadata = {
  title: '239re CRM',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className="relative">
        <Providers>
          {children}
          <PageLoader />
        </Providers>
      </body>
    </html>
  )
}
